name: VirtualChest
main: com.zone.vchest.VirtualChestPlugin
version:  5.6.2
authors: 
  - zonedabone
  - Balor
license: GPLv3
softdepend: [Vault]
description: >
            VirtualChest allows you to have a chest with you wherever you go.
commands:
 giftpost:
  description: master command
  aliases: gp
  usage: /<command>